# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
env:
  BRANCH: ${GITHUB_REF##*/}

  
on:
  push:
    branches:
      - main


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - uses: noliran/branch-based-secrets@v1
        with:
          secrets: SECRET_TOKEN
      - uses: actions/checkout@v2


      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ env.SECRET_TOKEN_NAME }}
